### ISSUE TITLE
Ruby on Rails Group Project Kanban Board

### ISSUE THREAD

**Issue by henask12** [Diegogagan2587/Recipe-app-bests-dishes#16]
This is the link for the project's Kanban:
https://github.com/users/Diegogagan2587/projects/3

Group members:
1. Diego Vidal Lopez @Diegogagan2587 => 20.5px
2. Henok Mekonnen @henask12  => 20.5px

**Comment by cynthiainga** [comment]
Hi @henask12 & @Diegogagan2587, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] All cards are assigned to team members ✔️ 
- [ ] Each card on the board has a descriptive title, the number of points in the \[Xpt\] prefix, and a description of the task ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
